### ISSUE TITLE
Bugs....

### ISSUE THREAD

**Issue by SublymeRick** [avadev/AvaTax-Calc-SOAP-PHP#15]
Samples/GetTaxTest.php - Line 161
$getTaxRequest needs to be changed to $getTaxResult

AvaTax/GetTaxRequest.php
Remove lines 118 - 172
(functions set properties that do not exist - looks like left overs from a copy / paste of the address class.)

AvaTax/GetTaxRequest.php
- This one caused me major problems, and maybe only on php7 but its definitely a problem on php7. 
Remove the &ref from &$line in the foreach loop on line 74 (prepare method) - The presence of that ampersand causes the lines array to be completely omitted from the SOAP request sent to the service resulting in a RANGE ERROR. I'm honestly not sure if removing the reference is the best fix but it seems to work for me.

**Comment by anyarms** [comment]
Fixed!
